### ISSUE TITLE
[NEW FEATURE BUG] `FindById` and `Find` return null if `_id` is longer than 255 bytes

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1610]
## `FindById` and `Find` return null if `_id` is longer than 255 bytes

**Version**

The latest master.

**Describe the bug**

`FindById` and `Find` with equivalent expression return null if `_id` is longer than 255 bytes

**Code to Reproduce**

```csharp
[Fact]
public void Index_Length_256()
{
    using var db = new LiteDatabase(":memory:");
    var col = db.GetCollection("test");

    var id = new string('x', 256);
    col.Insert(new BsonDocument() { ["_id"] = id });

    BsonDocument doc;

    doc = col.FindById(id);
    Assert.NotNull(doc); //! Actual: null

    doc = col.Find(BsonExpression.Create("_id = @0", id)).FirstOrDefault();
    Assert.NotNull(doc); //! Actual: null
}
```

**Expected behavior**

The above test should pass. It fails at either of two asserts.

NB The above test works if we use 255 instead of 256.

**Note**

This is the new issue, it is "unlocked" due to the recent new feature "index max length = 1023".

**Comment by lbnascimento** [comment]
@nightroman This issue was fixed in the master branch and its fix will be present in the next incremental release.

**Comment by nightroman** [comment]
Thank you. Please take a look at my comment there, https://github.com/mbdavid/LiteDB/commit/9afda23a01c0489748ae819f66f57a03feb33a05#commitcomment-38261472

**Comment by nightroman** [comment]
FYI. There are other issues with long indexes. One is similar to this (still not working even with the fix). Another is with rebuilding failing on a DB with long indexes (error is about duplicated indexes).

I cannot yet build nice reproducible cases.

**Comment by nightroman** [comment]
Interesting... It looks like due to this bug which was not yet fixed I now have a DB with duplicated long indexes (ids), kind of corrupted (no problem, it' not production stuff). Maybe other problems are due to these duplicated ids.

**Comment by nightroman** [comment]
Yes, this was the case, duplicated ids caused some problems (presumably).
After repairing the database I do not see the mentioned issues.

**Comment by lbnascimento** [comment]
@nightroman What do you mean by duplicated indexes?

**Comment by nightroman** [comment]
> @nightroman What do you mean by duplicated indexes?

Because of the bug in question (which is fixed now) I managed to produce duplicated indexes in my database. Because `FindById` and `Find` did not find existing indexes and LiteDB added duplicated. That is what happened, I think.

**Comment by nightroman** [comment]
In fact I corrupted the database due to this bug. I said "after repairing"... Now I can see that on repairing (clone of all data) I missed some documents. So repair also is not an option in such a case.

Anyway. It was not a production database and it is lost due to this bug. Not a big deal when the bug is fixed.
