### ISSUE TITLE
[BUG] Datetime daylight savings index issue 

### ISSUE THREAD

**Issue by p962** [mbdavid/LiteDB#1776]
**Version**
Latest.

**Bug Description**
A 'duplicate key' exception is thrown when inserting two objects with datetime set as an index. This occurs on a daylight savings adjustment boundary.

**Code to Reproduce**
```C#
using (var db = new LiteDatabase(@"Filename=DaylightSavingsTest.db; utc=yes") { UtcDate = true })
{
    var col = db.GetCollection<DateTimeRecord>("datetimedata");

    col.EnsureIndex(x => x.dateTimeKey, true);

    // These times are dependant on the timezone you are in. For this test to fail you system timezone needs to be set to Sydney/Australia (UTC+10).
    var firstDate = DateTime.Parse("4/04/2020 15:45:00Z");
    var secondDate = DateTime.Parse("4/4/2020 16:45:00Z");

    col.Insert(new DateTimeRecord() { dateTimeKey = firstDate });
    col.Insert(new DateTimeRecord() { dateTimeKey = secondDate }); // Duplicate Key, throws exception

}
```

**Expected behavior**
Insert should suceed, especially when dealing with UTC times.

**Additional context**

If you remove the **ToLocalTime()** from this function, the insert works as expected:

LiteDB/LiteDB/Utils/Extensions/BufferSliceExtensions.cs

```C#
public static DateTime ReadDateTime(this BufferSlice buffer, int offset)
{
    var ticks = buffer.ReadInt64(offset);

    if (ticks == 0) return DateTime.MinValue;
    if (ticks == 3155378975999999999) return DateTime.MaxValue;

    return new DateTime(buffer.ReadInt64(offset), DateTimeKind.Utc).ToLocalTime(); //ToLocalTime() causes this issue.
}
```

**Comment by lbnascimento** [comment]
@p962 I believe this has nothing to do with daylight saving. You're calling `EnsureIndex` with the second parameter being `true`, and this parameter (`unique`) is used to indicate whether every document in the collection will have a distinct value for the indexed field or not. Change it to `false` and it should work fine.

**Comment by p962** [comment]
@lbnascimento You are correct. In my haste to make a simplified example of the problem I copied the wrong datetime. I've corrected the above sample to reproduce the problem correctly.

**Comment by p962** [comment]
Both times are now distinct and seperated by an hour. This now throws the duplicate key exception even though both times in UTC are different. Because of daylight savings and the clock rolling back one hour over this period, both times (when converted to local) are considered the same.

```
    var firstDate = DateTime.Parse("4/04/2020 15:45:00Z");
    var secondDate = DateTime.Parse("4/4/2020 16:45:00Z");
```

**Comment by lbnascimento** [comment]
@p962 First of all, removing the `.ToLocalTime()` from `ReadDateTime` does not solve the issue for me, which is really weird.

I'm not sure this is actually a bug in LiteDB. The calls to `DateTime.Parse` return two dates with `Ticks` being equal to `637216515000000000`. The information that the two strings defined different moments in time is lost after the parsing.

I believe you could either force parsing to UTC or use `DateTimeOffset` with a custom serializer.

Forced parsing to UTC:
```C#
var utcDate = DateTime.Parse("4/04/2020 15:45:00Z", CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal);
```

Custom serializer for `DateTimeOffset`:
```C#
BsonMapper.Global.RegisterType<DateTimeOffset>
(
    serialize: obj =>
    {
        var doc = new BsonDocument();
        doc["DateTime"] = obj.DateTime.Ticks;
        doc["Offset"] = obj.Offset.Ticks;
        return doc;
    },
    deserialize: doc => new DateTimeOffset(doc["DateTime"].AsInt64, new TimeSpan(doc["Offset"].AsInt64))
);
```

A final tip: the `utc=yes` in your connection string is doing nothing. If you want to keep deserialized dates in UTC (instead of converting them to local time, which is the default behavior), you should run `db.UtcDate = false;` once for your datafile.

**Comment by p962** [comment]
@lbnascimento Thanks for your feedback, I really appreciate the comments and the tips. I was trying some suggestions from other comments before diving into the library to see what was going on.

My original code that caused the original issue was simply a UTC DateTime incremented every 15 minutes over the course of a year. I would then experience exceptions when the clock roll backward due to daylight savings despite using only UTC times.

Something like this (which you would expect to work):

```
 for (var theDate = DateTime.UtcNow; theDate < theDateAYearFromNow; theDate.AddMinutes(15))
 {
        // do something
 }
```

I feel `.ToLocalTime()` is an unnecessary step and will cause issues since mutliple UTC times map to the same local time. This is why I like to use UTC, to try and avoid these issues :)

**Comment by lbnascimento** [comment]
@p962 I may remove the `.ToLocalTime()` because it doesn't seem to be necessary (I'll run some tests), but removing it didn't fix issue for me.

I don't know about your real code, but for this sample code the issue seems to be in the `DateTime.Parse(...)` calls. If you debug the code, you'll see both dates end up having the same `Ticks` value (637216515000000000), so they are in fact identical. The dates are parsed as local dates by default, which causes these two different strings to be parsed as the same date.

**Comment by p962** [comment]
@lbnascimento Removing it fixed my original issue.

I also agree that the DateTime in the sample code has an issue with `DateTime.Parse(...)`. This is strange because the 'Z' denotes Zulu time and should represent a UTC time. It appears the Parse is effected by the timezone as well. This was a fluke because I was just trying to re-create the original issue. In any case I think removing the `.ToLocalTime()` is a good idea.
